### ISSUE TITLE
Generate pdf thumbnail on creation

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp#1242]
Create thumbnail image for a pdf file. Not sure it's easy, but it would be a nice improvement!

- on creation
- on import (I believe changing on creation should update this as well but you need to check)

**Comment by Defferrard** [comment]
Here is the library I've compared to each other : 

library|last update|convert only the 1st page|weekly downloads | stars
--|--|--|--|--
[pdf-thumbnail](https://www.npmjs.com/package/pdf-thumbnail) | 6 years ago | Yes | 4'155 | 29
[pdf-to-img](https://www.npmjs.com/package/pdf-to-img) | 7 days ago | Yes | 9'296 | 65
[pdf-img-convert.js](https://www.npmjs.com/package/pdf-img-convert) |  1 year ago | Yes | 22'874 | 159
[pdf2pic](https://www.npmjs.com/package/pdf2pic) | 7 months ago | Yes |  67'409 | 398
