### ISSUE TITLE
uploading image (> 20MB) crashes the backend

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp#175]
Need to ensure that we can handle this load for images. Weirdly, it doesn't happen for other file types, which means that there's something that is happening with the images.

**Comment by pyphilia** [comment]
The fix I've applied is to remove all buffered images and use streams instead. Thumbnails run now in sequence, and uploading files has a maximum number of tasks in parallel. From the frontend side, I've refactored the crop logic to avoid sending a bigger image (actually bigger than the original one).
