### ISSUE TITLE
Do not return password for GET /current member

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp#201]
Even though it is not a big leak (you get your own password) it is safer to not return it at all.

**Comment by ritikBhandari** [comment]
Hi,
Can I take up this issue?

**Comment by pyphilia** [comment]
Sure @ritikBhandari ! It will involve the schema validation of the member service based on fastify. 
Let me know if you have any question or if you have trouble when you install locally this project.

**Comment by victorggonzalez** [comment]
I found this solution for not returning the password value. The idea is to return true if user has a password or false if not. That way we can handle this boolean in the update password functionality
