### ISSUE TITLE
Switch to TypeORM

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp#273]
## @dialexo 

- metrics 
  - [ ]  refactor
  - [ ]  tests
  
- https://github.com/graasp/graasp-plugin-actions 
https://github.com/graasp/graasp-plugin-actions/pull/32
https://github.com/graasp/graasp-sdk/pull/32
https://github.com/graasp/graasp/pull/245
  - [ ]  refactor
  - [ ]  tests

- https://github.com/graasp/graasp-plugin-file 
  - [x]  refactor
  - [ ]  tests
- https://github.com/graasp/graasp-plugin-file-item  (should file and file-item be merged? )
  - [x]  refactor
  - [x]  tests
- https://github.com/graasp/graasp-plugin-etherpad 
  - [ ]  refactor
  - [ ]  tests
- https://github.com/graasp/graasp-plugin-h5p 
  - [ ]  refactor
  - [ ]  tests
 
- https://github.com/graasp/graasp-plugin-thumbnails 
  - [x]  refactor
  - [ ]  tests
- https://github.com/graasp/graasp-websockets 
  - [ ]  refactor
  - [ ]  tests

- https://github.com/graasp/graasp-plugin-item-zip 
  - [x]  refactor
  - [ ]  tests

## pyphilia

- https://github.com/graasp/graasp-plugin-recycle-bin 
  - [x]  refactor
  - [x]  tests
  
- https://github.com/graasp/graasp-plugin-hidden-items ---> item tag
  - [ ]  refactor
  - [ ]  tests

- https://github.com/graasp/graasp-plugin-categories 
  - [x]  refactor
  - [x]  tests

- apps
  - [x]  refactor
  - [x]  tests
- document item
  - [x]  refactor
  - [x]  tests
- link item
  - [x]  refactor
  - [x]  tests

- https://github.com/graasp/graasp-plugin-public --> item tag
  - [ ]  refactor
  - [ ]  tests
- item tags (necessary?)
  - [x]  refactor
  - [x]  tests
- https://github.com/graasp/graasp-plugin-item-login 
  - [x]  refactor
  - [x]  tests
- https://github.com/graasp/graasp-plugin-validation 
  - [x]  refactor
  - [ ]  tests

- https://github.com/graasp/graasp-plugin-invitations 
  - [x]  refactor
  - [x]  tests
  
- https://github.com/graasp/graasp-plugin-item-publish  (since it can become complex (keep track of versions) we have don't use item tag)
  - [x]  refactor
  - [x]  tests

- https://github.com/graasp/graasp-plugin-search 
  - [ ]  refactor
  - [ ]  tests

## @spaenleh 

- https://github.com/graasp/graasp-plugin-chatbox 
  - [x]  refactor
  - [x]  tests

- https://github.com/graasp/graasp-plugin-item-likes
  - [x]  refactor
  - [x]  tests

- item flagging
  - [x]  refactor
  - [x]  tests

Not necessary plugins (not used yet):

- https://github.com/graasp/graasp-plugin-subscriptions 
  - [ ]  refactor
  - [ ]  tests

Dropped plugins (not used anymore):

- https://github.com/graasp/graasp-plugin-admin 
  - [ ]  refactor
  - [ ]  tests

**Comment by pyphilia** [comment]
hidden items: this is quite difficult as it needs to be defined in the service layer (it needs to check the member permission) but impact quite different endpoints.
My current test implementation is:
- have a filter out function to reuse: this needs to get all best permissions for each item and filter out items that are hidden if user is a reader
- apply at the service layer for all impacted endpoints (get children, get shared, get published items, get descedants...)

**Comment by pyphilia** [comment]
memberships cannot be easily added in the entity of Item as it's based on `path` which is hierarchy based. `@OneToMany` and similar work based on equality, so it's "impossible" to get the parent membership affecting the children for example. Unless we do a manual join, which is less automatic.

**Comment by dialexo** [comment]
> memberships cannot be easily added in the entity of Item as it's based on `path` which is hierarchy based. `@OneToMany` and similar work based on equality, so it's "impossible" to get the parent membership affecting the children for example. Unless we do a manual join, which is less automatic.

Note for future reference: one idea is instead of having permission logic at the fetch level is to add the permission layer as the entry call of each controller function: the return type of the permission layer would only allow to perform operations on the corresponding item subtree. The repositories are not decorated on the main instance. If some other parts of the server needs to access a given data in the subtree, it thus must use the permissioned access layer.
