### ISSUE TITLE
Thumbnails of images with transparent background

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp#377]
How are images with transparent backgrounds handled when creating the thumbnails ? Is the background set to black ? What is the format of the generated thumbnails ?

**Comment by dialexo** [comment]
I think having transparent backgrounds is fine and is more flexible (the front-end can set its own backgrounds). We should keep svg where possible IMO, but the front-end interface should accept any image (e.g. for user uploads).

**Comment by spaenleh** [comment]
Agreed ! I checked and currently the thumbnails convert transparent background to black.
