### ISSUE TITLE
Add HTML (SCORM) support through sandboxed (?) iframe

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp#383]
Import single-file HTML pages as well as SCORM packages (probably not the full spec?)

- Q: can we reuse parts of the H5P implementation into a generic HTML content service?
- Q: security implications? What should we allow (is interweave enough)? What about e.g. JS simulations?
- Can we improve the isolation? e.g. generate s3 signed URL through postMessage API

**Comment by pyphilia** [comment]
We drop this issue because we're not planning to implement it anymore.
