### ISSUE TITLE
What is the purpose of the `.stagingcontainer` ?

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp#389]

**Comment by dialexo** [comment]
@spaenleh isn't it the Docker build for the production image? See https://github.com/search?q=repo%3Agraasp%2Fgraasp-deploy%20.stagingcontainer&type=code

But I agree it's a bit confusing. @morganridel is there any better approach?

**Comment by morganridel** [comment]
If it is the prod container I would just put a `Dockerfile` at the repo's root, or in a simple `docker` folder

**Comment by spaenleh** [comment]
Agree, this naming is a bit confusing. Also maybe we should add some comments inside the file to explain its purpose.
