### ISSUE TITLE
[export-actions] Downloading actions with Firefox fails

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp#445]
When downloading actions with Firefox (v101.0.1), the browser downloads a truncated file with a wrong filename.

### Example filename:

Expected (downloaded with Chrome): `2022-07-05T14_08_26.zip`
Result with Firefox: `2022-07-05T14 08 26.134Z`

**Comment by pyphilia** [comment]
@swouf is it still the case?

**Comment by swouf** [comment]
It is working now. I just tried.

I close the issue.
