### ISSUE TITLE
Transparency in thumbnails turn to black

### ISSUE THREAD

**Issue by swouf** [graasp/graasp#461]
When making a thumbnail, transparent parts of PNGs turn to black. This looks weird in the interface which has mostly white backgrounds.

I don't know if the transparency is kept in the thumbnail which would require adapting [the thumbnail pipeline](https://github.com/graasp/graasp/blob/280dfc553d68703dfa8a8bec1c051b6a9ac6ca3e/src/services/thumbnail/utils.ts#L11-L26). Otherwise, this issue may need to be fixed into the builder.

**Comment by spaenleh** [comment]
Same issue is described in #377
