### ISSUE TITLE
[export-zip] Single files are exported as zip

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp#567]
Is there a reason why when downloading a single file it is sent as a zip ?

Question:
- Can we not wrap it in a zip ? This would help to open pdfs directly in the browser (when supported by the OS and the preference of the user).

**Comment by pyphilia** [comment]
Yes I think it's possible, not too difficult to do I would say.

**Comment by pyphilia** [comment]
ref https://github.com/graasp/graasp/issues/1130
