### ISSUE TITLE
[mail] Invitation mail title is missing the itemName

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp#605]
https://github.com/graasp/graasp/blob/522c1b8f0844cf8289af1ae02b6e1666a0027bb2/src/services/invitation/service.ts#L46C1-L46C1

`The item {{itemName}} was shared with you on Graasp`

**Comment by dialexo** [comment]
This was fixed by https://github.com/graasp/graasp/pull/600.

See https://github.com/graasp/graasp/pull/600/commits/79decd305e76d8091ea63d57621c583156fa41a8#diff-ff5eec1717ea70fed1943176f2e27b814655eb86a8d3b1c8ef1fb14b5c221383
