### ISSUE TITLE
Add filter on hidden in descendents call

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp#889]

**Comment by pyphilia** [comment]
currently descendants return `hidden` tag since it returns packed item. Maybe this is enough? But it's true that filtering at the backend side can improve network load, tho it will require a join on tags in the database (so heavier on db).

**Comment by spaenleh** [comment]
@pyphilia If descendants add the hidden in packed item, then we could filter out these elements before returning the data ? Maybe it would be cleaner to add it in the initial query instead of with a pass after getting the data from the db though.

It is true that the front end could do the filtering too, but I think it goes agains the idea that whatever is returned from the backend should be usable by the player. I do not think that having to filter before computing the navigation is a good thing to do in the frontend.

**Comment by pyphilia** [comment]
closed with https://github.com/graasp/graasp/issues/889
